### ISSUE TITLE
Filterable TODO list view

### ISSUE THREAD

**Issue by schoettl** [200ok-ch/organice#141]
The agenda view only lists items that have active timestamps. However, we need see a (flat) list of tasks that can be narrowed down by filters.

For my exact use case, see below.

**Two possible implementations:**

A)

- Next to (or integrated in) the "Show agenda" button there could be a "Show task list" button.
- A modal should show the task list (read-only, like the agenda).
- A click on an item should jump to the item (like in the agenda).
- At the top of the pop-up there should be a filter interface to filter for tags, regex, ... [1]

B)

- At the top of the app, next to undo/redo, there should be a filter/search icon that opens an inline filter text input.
- This filter should narrow down the main item view and could work similar to `org-sparse-tree` [2]

As far I understand the Sparse tree feature (I'm not an emacs user yet), it folds all headlines except the ones, that are selected by the filter. But for sparse trees, it seems that we cannot filter for tag AND property AND TODO-state, right? A combined AND-filter (like in GitHub issues) would be important for me.

Wich approach do you think is better?

**Filter logic and syntax:**
For me, the most important options for filtering are:

1. TODO state
2. case-insensitive match headline text
3. tags
4. property value search

Points 1. and 2. can be combined:
- "smart-case" search
- `TODO` is case-sensitive search in the headline text (because it contains upper-case letters)
- `abc` is case-insensitive search in the headline text (because it's all lower-case)
- for both forms, `|` means a logical OR, e.g. `TODO|DEFERRED`
- space inbetween words means logical AND

Syntax suggestion for points 3. and 4.:
- search for tag: `:tagx` (like orgmode tag syntax)
- search for property with value: `:property:val` where val matches even if it's only a part of value (like orgmode property syntax)
- the `:` triggers the completions/suggestions for tags, property names, and property values

**Background – our use-case:**
The workshop supervisor should be able to work with a tablet and

- [x] look for tasks that fit for a specific employee
- [ ] graph view for dependencies inbetween task (similar to org2dot [3])
- [x] share a headline item (via e-mail) e.g. to ask a question about it
- [x] see status of a task with subtasks (`[%] [/]`)
- [x] see the agenda (`DEADLINE:`/`SCHEDULED:`)
- [x] quickly add tasks (-> capture templates)
- [x] add complex tasks from a template (the "build plan" for an order with sub tasks)
- [x] manage assignees (-> properties and smart property value completion)

[1] https://orgmode.org/manual/Filtering_002flimiting-agenda-items.html
[2] https://orgmode.org/manual/Sparse-trees.html
[3] https://gist.github.com/schoettl/ca1f729d5472dcff43e2139def941b40

**Comment by munen** [comment]
> The agenda view only lists items that have active timestamps. 

Slight correction. Your statement is correct for Emacs Org mode. In organice, there's this open issue: https://github.com/200ok-ch/organice/issues/42

> Wich approach do you think is better?

I think that option B is what the default UX should be. To be honest, I don't really understand option A, even(;

In any case, having a filter/search icon on the top headline is definitively something that's easy to understand and something that was on my roadmap to build at some point. I'd be super stoked if someone beats me to building it!

As for your understanding of the Emacs Org mode sparse tree, I confirm your description of how it works.

I like your suggestions on how a simple input field can be utilized. The way you describe it every user will be able to do it without having a lot of icons or documentation to read.

If I may suggest: Having this kind of search is a great option to actually build in a test driven manner. That'll help you to find the right kind of data and filter it down.

In any case, I'm very much looking forward to an implementation and would be happy to help out with writing tests and doing manual tests on bigger Org files!

**Comment by schoettl** [comment]
> I think that option B is what the default UX should be. To be honest, I don't really understand option A, even(;

I mean like this: https://imgur.com/XsUBlK9
Additional to the agenda.

This way, the tasks would probably displayed more compact than with the sparse tree. I'm not sure yet about A) and B). But the filter part would be the same anyway.

**Comment by schoettl** [comment]
Note:

A nice placeholder text for the UI filter input would be something like to show all features of the filter:

```
<input placeholder="..." ...>

e.g. TODO|FIXME doc :simple|easy :assignee:nobody|none
```

**Comment by munen** [comment]
Having a placeholder to describe the syntax is a great idea!
