### ISSUE TITLE
Write tests for "Multiple File" epic

### ISSUE THREAD

**Issue by munen** [200ok-ch/organice#605]
Things to write tests for:

- [ ] (not) displaying things in Agenda, Search, Task-List with and without file settings
- [ ] jumping to a header in another file from Agenda, Search, Task-List
- [ ] capturing to another file with various capture template settings
- [ ] refiling to another file with various file settings
