### ISSUE TITLE
Document 'multiple file' epic

### ISSUE THREAD

**Issue by munen** [200ok-ch/organice#606]
List of things to document after merging:

- [ ] General functionality and awesomeness of this change
  - [ ]  Add to documentation that results are limited to 200 headers
- [ ] UX for developers: How to cope with slowing Redux (https://github.com/200ok-ch/organice/pull/570#issuecomment-735434357)

Think about and maybe drop follow up issues:

- [ ] Configure capture templates to be shown 'global' or in 'buffer'. Discussion:
  - https://github.com/200ok-ch/organice/pull/570#issuecomment-735438317
  - https://github.com/200ok-ch/organice/pull/570#issuecomment-735446594
  - https://github.com/200ok-ch/organice/pull/570#issuecomment-735654214

**Comment by munen** [comment]
A minimal introduction was added here: https://github.com/200ok-ch/organice/pull/632
